modLoader="kotlinforforge"
loaderVersion="[1.6,)"
license='MIT'

[[mods]]
modId="data_gen_dsl"
version="${file.jarVersion}"
displayName="Data Generator DSL"
logoFile="dgdsl.png"
credits=""
authors="ChAoS-UnItY"
description='''
    Developer-friendly domain specific language for data generator purpose.
'''
